// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

function App(Props) {
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  var onClickIncrease = function (evt) {
    return Curry._1(setCount, (function (_prev) {
                  return _prev + 1 | 0;
                }));
  };
  var onClickDecrease = function (evt) {
    return Curry._1(setCount, (function (_prev) {
                  return _prev - 1 | 0;
                }));
  };
  return React.createElement(React.Fragment, undefined, React.createElement("h1", undefined, "Simple Counter"), React.createElement("p", undefined, React.createElement("span", undefined, String(match[0])), React.createElement("button", {
                      type: "button",
                      onClick: onClickIncrease
                    }, "increase"), React.createElement("button", {
                      type: "button",
                      onClick: onClickDecrease
                    }, "decrease")));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
