// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";
import * as App$ProjectName from "./App.bs.js";

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(React.createElement(App$ProjectName.make, {}), root);
}

export {
  
}
/* root Not a pure module */
